name = "EDUC_BiDiM_IRM"
uuid = "69b5d747-056c-48f8-8168-aacde1be9172"
authors = ["aTrotier <a.trotier@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
